tasks:
  - init: npm install
    command: |
      npm run dev
ports:
  - port: 3000
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - snowpackjs.astro
    - oouo-diogo-perdigao.docthis
    - hookyqr.beautify
    - ms-azuretools.vscode-docker
    - cschleiden.vscode-github-actions
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - runem.lit-plugin
    - codeandstuff.package-json-upgrade
    - esbenp.prettier-vscode
    - gencer.html-slim-scss-css-class-completion
    - jerrygoyal.shortcut-menu-bar
    - dotjoshjohnson.xml
